export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './coffeeController.service';
import { CoffeeControllerService } from './coffeeController.service';
export * from './coffeeMugController.service';
import { CoffeeMugControllerService } from './coffeeMugController.service';
export * from './courseController.service';
import { CourseControllerService } from './courseController.service';
export * from './enrollmentController.service';
import { EnrollmentControllerService } from './enrollmentController.service';
export * from './examController.service';
import { ExamControllerService } from './examController.service';
export * from './examRegistrationController.service';
import { ExamRegistrationControllerService } from './examRegistrationController.service';
export * from './finalGradeController.service';
import { FinalGradeControllerService } from './finalGradeController.service';
export * from './roomAvailabilityController.service';
import { RoomAvailabilityControllerService } from './roomAvailabilityController.service';
export * from './roomController.service';
import { RoomControllerService } from './roomController.service';
export * from './studentController.service';
import { StudentControllerService } from './studentController.service';
export * from './studentCourseController.service';
import { StudentCourseControllerService } from './studentCourseController.service';
export * from './studentExamController.service';
import { StudentExamControllerService } from './studentExamController.service';
export * from './teacherAvailabilityController.service';
import { TeacherAvailabilityControllerService } from './teacherAvailabilityController.service';
export * from './teacherController.service';
import { TeacherControllerService } from './teacherController.service';
export * from './thesisController.service';
import { ThesisControllerService } from './thesisController.service';
export const APIS = [AuthControllerService, CoffeeControllerService, CoffeeMugControllerService, CourseControllerService, EnrollmentControllerService, ExamControllerService, ExamRegistrationControllerService, FinalGradeControllerService, RoomAvailabilityControllerService, RoomControllerService, StudentControllerService, StudentCourseControllerService, StudentExamControllerService, TeacherAvailabilityControllerService, TeacherControllerService, ThesisControllerService];
