/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoffeeDto { 
    id?: number;
    origin?: string;
    brewMethod?: CoffeeDto.BrewMethodEnum;
}
export namespace CoffeeDto {
    export type BrewMethodEnum = 'ESPRESSO' | 'FILTER' | 'AEROPRESS';
    export const BrewMethodEnum = {
        Espresso: 'ESPRESSO' as BrewMethodEnum,
        Filter: 'FILTER' as BrewMethodEnum,
        Aeropress: 'AEROPRESS' as BrewMethodEnum
    };
}


