/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExamRegistrationDto { 
    id?: string;
    studentId?: string;
    examId?: string;
    chosenSlot?: ExamRegistrationDto.ChosenSlotEnum;
}
export namespace ExamRegistrationDto {
    export type ChosenSlotEnum = 'PRIMARY' | 'SECONDARY';
    export const ChosenSlotEnum = {
        Primary: 'PRIMARY' as ChosenSlotEnum,
        Secondary: 'SECONDARY' as ChosenSlotEnum
    };
}


