/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExamDto { 
    id?: string;
    courseId?: string;
    teacherId?: string;
    examType?: ExamDto.ExamTypeEnum;
    examFormat?: ExamDto.ExamFormatEnum;
    group?: string;
    duration?: number;
    primaryDate?: string;
    secondaryDate?: string;
    room?: string;
}
export namespace ExamDto {
    export type ExamTypeEnum = 'PARTIAL' | 'FINAL' | 'RESIT';
    export const ExamTypeEnum = {
        Partial: 'PARTIAL' as ExamTypeEnum,
        Final: 'FINAL' as ExamTypeEnum,
        Resit: 'RESIT' as ExamTypeEnum
    };
    export type ExamFormatEnum = 'WRITTEN' | 'PRACTICAL';
    export const ExamFormatEnum = {
        Written: 'WRITTEN' as ExamFormatEnum,
        Practical: 'PRACTICAL' as ExamFormatEnum
    };
}


