/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentDto { 
    id?: string;
    nationalId?: string;
    firstName?: string;
    lastName?: string;
    dateOfBirth?: string;
    email?: string;
    group?: string;
}

