/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentExamDto { 
    id?: string;
    studentId?: string;
    examId?: string;
    studentName?: string;
    group?: string;
    sessionGrade?: string;
    resitGrade?: string;
    gradeStatus?: StudentExamDto.GradeStatusEnum;
}
export namespace StudentExamDto {
    export type GradeStatusEnum = 'PASSED' | 'FAILED' | 'PENDING';
    export const GradeStatusEnum = {
        Passed: 'PASSED' as GradeStatusEnum,
        Failed: 'FAILED' as GradeStatusEnum,
        Pending: 'PENDING' as GradeStatusEnum
    };
}


